// Auto-generated content constants - DO NOT EDIT MANUALLY
// Last updated: 2025-08-07T10:45:12.687Z
// Generated by: scripts/sync-content-across-platforms.js

export const APP_CONSTANTS = {
  API_BASE_URL: 'https://dahabiyatnilecruise.com',
  
  DEVELOPER: {
    NAME: 'Just X Development',
    COMPANY: 'Just X',
    PHONE: '+201200958713',
    EMAIL: 'developer@justx.com',
    WEBSITE: 'https://justx.com',
    BRANDING_TEXT: 'Crafted with love in the land of the Pharaohs by Just X',
    LOGO: '/images/logo-white.png'
  },
  
  COMPANY: {
    NAME: 'Cleopatra Dahabiyat',
    ADDRESS: 'Luxor, Egypt',
    PHONE: '+20 123 456 789',
    EMAIL: 'info@cleopatradahabiyat.com'
  },
  
  ITINERARIES: {
    HERO_TITLE: 'Discover Ancient Egypt',
    HERO_SUBTITLE: 'Journey Through Time on the Eternal Nile',
    EMPTY_STATE_TITLE: 'No Journeys Found',
    EMPTY_STATE_DESCRIPTION: 'We could not find any itineraries matching your criteria. Please adjust your filters or contact us to create a custom journey just for you.'
  }
};

export default APP_CONSTANTS;
